[package]
name = "GBFPGA-Minecraft"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { version = "2.9.4", features = ["serde"] }
postcard = { version = "1.1.3", features = ["alloc"] }
serde = { version = "1.0.228", features = ["derive"] }
